services:
  db:
    image: postgres:18
    container_name: ecommerce
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql
    shm_size: 128mb

volumes:
  postgres_data:

